#theme: jekyll-agency

url    : "https://ryan-candido-1.github.io"
baseurl: ""

title      : Ryan Cândido
email      : ""
description: "Página pessoal para trabalho."
author     : Ryan Do Carmo Cândido

locale: "pt-BR"

analytics:
  google:

collections:
  portfolio:

markdown: kramdown

# Uncomment following line to use Formspree form ID based URL instead of email based URL
# Details: https://help.formspree.io/hc/en-us/articles/360017735154-How-to-prevent-spam
# formspree_form_path: "f/a_form_id”
